server:
  port: 7016
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/medical_yzs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: r2to%yz%a
  cache:
    type: redis  # 可选 redis、none、ehcache
  redis:
    host: redis # server host
    #Auth: bW9Ivzt0CAQdoJTDZ2wAnduvi
    port: 7420
    password: bW9Ivzt0CAQdoJTDZ2wAnduvi
    database: 0
jwtUtils:
  id: jwt
  secret: 6686df7fc3a34e26a61c034d5ec82488
  ttlMillis: 3600000



# 报表集成
report:
  dataease:
    username: wdmpk
    password: kjuuIYcARhyk+R5Q1s8QLwmZzfeoRgoYGHaIFzsoKD10nNbEukHG2hxieAqrHD/tN0IpsBOTEIFbnn5uIwM+tw==
    frontend:
      host: localhost
      port: 9528
      useSSLLink: 0
    backend:
      host: localhostx
      port: 8081
      useSSLLink: 0
    rsa_public_key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANL378k3RiZHWx5AfJqdH9xRNBmD9wGD2iRe41HdTNF8RUhNnHit5NpMNtGL0NPTSSpPjjI1kJfVorRvaQerUgkCAwEAAQ==
